import express from "express";
import { requireSignIn } from "../middlewares/authMiddleware.js";
import { createDriverContact, confirmMission, createSafetyAction, getActiveRide, getRide, listMyRides, listRideCalls, listRideMessages, sendRideMessage, transitionRide, updateMessageReceipt } from "../controllers/rideController.js";
import { contactRateLimit, messageRateLimit } from "../middlewares/marketplaceRateLimit.js";

const router = express.Router();
router.use(requireSignIn);
router.post("/contact", contactRateLimit, createDriverContact);
router.get("/active", getActiveRide);
router.get("/mine", listMyRides);
router.get("/:rideId", getRide);
router.post("/:rideId/confirm", contactRateLimit, confirmMission);
router.patch("/:rideId/status", transitionRide);
router.get("/:rideId/calls", listRideCalls);
router.get("/:rideId/messages", listRideMessages);
router.post("/:rideId/messages", messageRateLimit, sendRideMessage);
router.patch("/:rideId/messages/:messageId/receipt", updateMessageReceipt);
router.post("/:rideId/report", createSafetyAction("report"));
router.post("/:rideId/block", createSafetyAction("block"));
export default router;
