import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import multer from "multer";
import { generateStorage } from "./multerFunction.js";
import { deleteS3Object } from "./s3Storage.js";

// Voice notes live under their own prefix so they can be identified and
// cleaned up independently of avatars/documents. File names are generated by
// the shared storage helper (timestamp + sanitized base name) and never
// contain participant identifiers.
export const CHAT_AUDIO_DESTINATION = "public/chat-audio";

const backendRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

/** Absolute local directory for chat audio (used for streaming + cleanup). */
export const chatAudioRootPath = path.join(backendRoot, CHAT_AUDIO_DESTINATION);

const AUDIO_MIME_TYPES = new Set([
  "audio/mp4",
  "audio/m4a",
  "audio/x-m4a",
  "audio/aac",
  "audio/mp4a-latm",
  "audio/mpeg",
  "audio/3gpp",
]);

const parsePositiveInt = (value, fallback) => {
  const parsed = Number.parseInt(value ?? "", 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
};

// Configurable through the environment; defaults match the product spec.
export const CHAT_AUDIO_MAX_FILE_SIZE =
  parsePositiveInt(process.env.CHAT_VOICE_MAX_FILE_SIZE_MB, 5) * 1024 * 1024;
export const CHAT_AUDIO_MAX_DURATION_SECONDS = parsePositiveInt(
  process.env.CHAT_VOICE_MAX_DURATION_SECONDS,
  120
);

const storage = generateStorage(CHAT_AUDIO_DESTINATION);

export const chatAudioUpload = multer({
  storage,
  limits: { fileSize: CHAT_AUDIO_MAX_FILE_SIZE, files: 1 },
  fileFilter: (req, file, callback) => {
    if (!AUDIO_MIME_TYPES.has(file.mimetype)) {
      const error = new Error("Only AAC/M4A voice recordings are allowed");
      error.statusCode = 415;
      error.code = "UNSUPPORTED_AUDIO_TYPE";
      return callback(error);
    }
    callback(null, true);
  },
});

export const handleChatAudioUpload = (middleware) => (req, res, next) => {
  middleware(req, res, (error) => {
    if (!error) return next();
    const tooLarge =
      error instanceof multer.MulterError && error.code === "LIMIT_FILE_SIZE";
    if (!tooLarge && !error.statusCode) {
      // Unexpected storage failure: let the global handler report it.
      return next(error);
    }
    return res.status(tooLarge ? 413 : error.statusCode || 400).json({
      success: false,
      code: tooLarge
        ? "VOICE_FILE_TOO_LARGE"
        : error.code || "VOICE_UPLOAD_FAILED",
      message: tooLarge
        ? `Voice message must not exceed ${CHAT_AUDIO_MAX_FILE_SIZE / (1024 * 1024)} MB`
        : error.message,
    });
  });
};

/**
 * Removes an uploaded chat-audio file. Used when a message row could not be
 * created (or already exists through idempotent retry) so orphaned bytes do
 * not accumulate in storage.
 */
export const removeChatAudioUpload = async ({ storage: storageKind, key }) => {
  if (!key) return;
  if (storageKind === "s3") {
    await deleteS3Object(key);
    return;
  }
  await fs.unlink(path.join(chatAudioRootPath, path.basename(key))).catch((error) => {
    if (error?.code !== "ENOENT") throw error;
  });
};
